# Generated by Django 3.1.7 on 2021-03-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210324_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
